name: Build for Manual Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present

      - name: Run type check
        run: npm run typecheck --if-present

      - name: Run tests
        run: npm test -- --coverage --watchAll=false --passWithNoTests

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build/
          retention-days: 7

      - name: Deploy Instructions
        run: |
          echo "✅ Build completed successfully!"
          echo "📦 Build files are available as artifacts"
          echo "📋 To deploy manually:"
          echo "   1. Download build artifacts from this workflow"
          echo "   2. Extract and upload contents to your cPanel public_html folder"
          echo "   3. Or wait for automatic FTP deployment once secrets are configured"