name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        REACT_APP_ENVIRONMENT: production
        REACT_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        REACT_APP_GOOGLE_ANALYTICS_ID: ${{ secrets.GA_ID }}
        REACT_APP_API_BASE_URL: ${{ secrets.API_BASE_URL }}
        REACT_APP_ENABLE_ANALYTICS: true
        REACT_APP_ENABLE_ERROR_REPORTING: true
        REACT_APP_ENABLE_PERFORMANCE_MONITORING: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/

  deploy-to-cpanel:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: tilak@bluecascadeceramics.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
